server:
  port: 8085

spring:
  application:
    name: qa
  datasource:
    url: jdbc:mysql://localhost:3306/qa
    username: root
    password: aA1@9876
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints.web.exposure.include=*