server:
  port: 8085

spring:
  threads:
    virtual:
      enabled: true

  application:
    name: qa
  datasource:
    url: jdbc:mysql://localhost:3306/qa
    username: ${QA_DB_USER}
    password: ${QA_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:changelog/master.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc.datasource: INFO
    com.zaxxer.hikari: INFO  # For HikariCP
